"""
Unit test suite for Stage 4: Submission (scripts/submit.py).
"""

import os
import sys
import unittest
from unittest.mock import MagicMock, patch

# Add scripts directory to sys.path
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts"))

import submit


class TestCandidateSelection(unittest.TestCase):
    def test_find_submittable_issues_query(self):
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value.__enter__.return_value = mock_cursor
        mock_cursor.fetchall.return_value = [
            (1, 100, 0.85, True, 0.80, {}, "gemini-2.5-flash", "resilient/1/gemini", 1, 1, "Issue Title", "Issue Body", 5, "org/repo", "fork/repo", "main", "python")
        ]

        candidates = submit.find_submittable_issues(mock_conn, min_score=0.70)
        self.assertEqual(len(candidates), 1)
        mock_cursor.execute.assert_called_once()
        query_sql = mock_cursor.execute.call_args[0][0]
        self.assertIn("e.composite_score >= %s", query_sql)
        self.assertIn("LEFT JOIN pr_submissions prs", query_sql)


class TestDailyCaps(unittest.TestCase):
    def test_within_daily_caps(self):
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value.__enter__.return_value = mock_cursor
        mock_cursor.fetchone.side_effect = [(3,), (1,)]  # global_count=3, repo_count=1

        can_submit, reason = submit.check_daily_caps(mock_conn, repo_id=5)
        self.assertTrue(can_submit)
        self.assertIn("Within budget caps", reason)

    def test_global_cap_exceeded(self):
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value.__enter__.return_value = mock_cursor
        mock_cursor.fetchone.return_value = (10,)  # global_count=10

        can_submit, reason = submit.check_daily_caps(mock_conn, repo_id=5)
        self.assertFalse(can_submit)
        self.assertIn("Global 24h submission cap reached", reason)

    def test_repo_cap_exceeded(self):
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value.__enter__.return_value = mock_cursor
        mock_cursor.fetchone.side_effect = [(5,), (2,)]  # global_count=5, repo_count=2

        can_submit, reason = submit.check_daily_caps(mock_conn, repo_id=5)
        self.assertFalse(can_submit)
        self.assertIn("Repo 24h submission cap reached", reason)


class TestPRBodyFormatting(unittest.TestCase):
    def test_pr_body_contains_disclosure_and_fix(self):
        body, disclosure = submit.build_pr_body(
            issue_num=42,
            issue_title="Fix login bug",
            agent_name="gemini-2.5-flash",
            composite_score=0.88,
            reviewer_score=0.85,
            tests_passed=True,
        )
        self.assertIn("Fixes #42", body)
        self.assertIn("Passed ✅", body)
        self.assertIn("0.88", body)
        self.assertIn("automatically generated by **Resilient**", disclosure)
        self.assertIn(disclosure, body)


class TestExistingPROrchestration(unittest.TestCase):
    def test_existing_pr_detection(self):
        mock_session = MagicMock()
        mock_resp = MagicMock()
        mock_resp.status_code = 200
        mock_resp.json.return_value = [{"html_url": "https://github.com/org/repo/pull/12", "number": 12}]
        mock_session.get.return_value = mock_resp

        with patch("submit.gh_get", return_value=mock_resp):
            exists, pr_url, pr_num = submit.check_existing_pr(mock_session, "org/repo", "fork", "branch")
            self.assertTrue(exists)
            self.assertEqual(pr_url, "https://github.com/org/repo/pull/12")
            self.assertEqual(pr_num, 12)


class TestSubmissionPipeline(unittest.TestCase):
    def test_submit_issue_disallowed_policy(self):
        mock_conn = MagicMock()
        mock_cursor = MagicMock()
        mock_conn.cursor.return_value.__enter__.return_value = mock_cursor
        mock_session = MagicMock()

        candidate = (1, 100, 0.85, True, 0.80, {}, "gemini-2.5-flash", "resilient/1/gemini", 1, 1, "Issue Title", "Issue Body", 5, "org/repo", "fork/repo", "main", "python")

        with patch("submit.check_ai_policy", return_value="disallowed"):
            submit.submit_issue(mock_conn, mock_session, candidate)
            mock_cursor.execute.assert_called_once()
            self.assertIn("status = 'skipped'", mock_cursor.execute.call_args[0][0])
            mock_conn.commit.assert_called_once()


if __name__ == "__main__":
    unittest.main()
