"""
Submission stage.

Runs after evaluation (see .github/workflows/submit.yml). Responsibilities:
  1. Find evaluated agent fixes with composite_score >= 0.70 that haven't been submitted yet.
  2. Authenticate using resilient-bot (GitHub App) or PAT fallback.
  3. Validate repository AI policy (check_ai_policy).
  4. Enforce daily submission caps (max 2 PRs per repo, max 10 PRs globally per 24 hours).
  5. Check if a PR already exists for the branch to ensure idempotency.
  6. Create upstream Pull Request with mandatory AI-involvement disclosure text.
  7. Record row in pr_submissions table and update issues.status = 'submitted'.
"""

import os
import sys
import time
from datetime import datetime, timezone

import psycopg2

from github_utils import (
    GITHUB_API,
    check_ai_policy,
    create_github_session,
    get_app_installation_token,
    gh_get,
    gh_post,
    sanitize_token,
)

DB_URL = ""
DISPATCH_TOKEN = ""
APP_ID = ""
APP_PRIVATE_KEY = ""

MAX_PRS_PER_REPO_PER_DAY = 2
MAX_PRS_GLOBAL_PER_DAY = 10
MIN_COMPOSITE_SCORE = 0.70

DEFAULT_DISCLOSURE = (
    "> [!NOTE]\n"
    "> This pull request was automatically generated by **Resilient** using an AI coding agent.\n"
    "> All proposed code changes have passed repository unit testing and automated static analysis.\n"
    "> Please review carefully before merging."
)


def find_submittable_issues(conn, min_score=MIN_COMPOSITE_SCORE):
    """Find issues with an evaluated run score >= min_score that lack a submission row."""
    with conn.cursor() as cur:
        cur.execute("""
            SELECT DISTINCT ON (i.id)
                   e.id AS eval_id, e.run_id, e.composite_score, e.tests_passed, e.reviewer_score, e.reviewer_notes,
                   r.agent_name, r.branch_name,
                   i.id AS issue_id, i.github_issue_number, i.title AS issue_title, i.body AS issue_body,
                   repo.id AS repo_id, repo.full_name AS upstream_full_name, repo.fork_full_name, repo.default_branch, repo.language
            FROM evaluations e
            JOIN runs r ON r.id = e.run_id
            JOIN issues i ON i.id = r.issue_id
            JOIN repos repo ON repo.id = i.repo_id
            LEFT JOIN pr_submissions prs ON prs.issue_id = i.id
            WHERE prs.id IS NULL
              AND i.status IN ('discovered', 'dispatched')
              AND repo.is_active = TRUE
              AND e.composite_score >= %s
            ORDER BY i.id ASC, e.composite_score DESC, e.id ASC
        """, (min_score,))
        return cur.fetchall()


def check_daily_caps(conn, repo_id: int) -> tuple[bool, str]:
    """Check whether submitting another PR violates per-repo or global 24h caps.

    Returns:
        (can_submit: bool, reason: str)
    """
    with conn.cursor() as cur:
        # Check global limit
        cur.execute("""
            SELECT COUNT(*) FROM pr_submissions
            WHERE submitted_at >= now() - INTERVAL '24 hours'
        """)
        global_count = cur.fetchone()[0]
        if global_count >= MAX_PRS_GLOBAL_PER_DAY:
            return False, f"Global 24h submission cap reached ({global_count}/{MAX_PRS_GLOBAL_PER_DAY})"

        # Check per-repo limit
        cur.execute("""
            SELECT COUNT(*) FROM pr_submissions prs
            JOIN issues i ON i.id = prs.issue_id
            WHERE i.repo_id = %s AND prs.submitted_at >= now() - INTERVAL '24 hours'
        """, (repo_id,))
        repo_count = cur.fetchone()[0]
        if repo_count >= MAX_PRS_PER_REPO_PER_DAY:
            return False, f"Repo 24h submission cap reached for repo #{repo_id} ({repo_count}/{MAX_PRS_PER_REPO_PER_DAY})"

    return True, "Within budget caps"


def check_existing_pr(session, upstream_full_name: str, fork_owner: str, branch_name: str) -> tuple[bool, str | None, int | None]:
    """Check if an upstream PR already exists for head branch (fork_owner:branch_name).

    Returns:
        (exists: bool, pr_url: str | None, pr_number: int | None)
    """
    head_ref = f"{fork_owner}:{branch_name}"
    url = f"{GITHUB_API}/repos/{upstream_full_name}/pulls"
    try:
        resp = gh_get(session, url, params={"head": head_ref, "state": "all"})
        if resp.status_code == 200:
            prs = resp.json()
            if prs and len(prs) > 0:
                pr = prs[0]
                return True, pr.get("html_url"), pr.get("number")
    except Exception as exc:
        print(f"Warning checking existing PR: {exc}", file=sys.stderr)

    return False, None, None


def build_pr_body(issue_num: int, issue_title: str, agent_name: str, composite_score: float,
                  reviewer_score: float, tests_passed: bool | None) -> tuple[str, str]:
    """Format PR body markdown and mandatory disclosure text.

    Returns:
        (full_pr_body: str, disclosure_text: str)
    """
    tests_str = "Passed ✅" if tests_passed is True else ("Failed ❌" if tests_passed is False else "No automated tests detected ⚠️")
    disclosure = DEFAULT_DISCLOSURE

    body = (
        f"Fixes #{issue_num}\n\n"
        f"### Summary\n"
        f"Automated resolution for **#{issue_num}: {issue_title}** generated by **{agent_name}**.\n\n"
        f"### Verification Details\n"
        f"- **Unit Tests:** {tests_str}\n"
        f"- **Code Quality Score:** {reviewer_score:.2f} / 1.00\n"
        f"- **Composite Score:** {composite_score:.2f} / 1.00\n\n"
        f"---\n"
        f"{disclosure}\n"
    )
    return body, disclosure


def create_upstream_pr(session, upstream_full_name: str, fork_owner: str, branch_name: str,
                       default_branch: str, title: str, body: str) -> tuple[str, int]:
    """Post Pull Request creation to GitHub REST API.

    Returns:
        (pr_url: str, pr_number: int)
    """
    url = f"{GITHUB_API}/repos/{upstream_full_name}/pulls"
    head = f"{fork_owner}:{branch_name}"
    payload = {
        "title": title,
        "body": body,
        "head": head,
        "base": default_branch,
    }
    resp = gh_post(session, url, json=payload)
    if resp.status_code in (200, 201):
        pr_data = resp.json()
        return pr_data["html_url"], pr_data["number"]
    else:
        raise RuntimeError(f"GitHub PR creation failed ({resp.status_code}): {resp.text}")


def submit_issue(conn, session, candidate):
    """Process single issue submission within a database transaction."""
    (eval_id, run_id, composite_score, tests_passed, reviewer_score, reviewer_notes,
     agent_name, branch_name, issue_id, issue_num, issue_title, issue_body,
     repo_id, upstream_full_name, fork_full_name, default_branch, language) = candidate

    print(f"Processing candidate issue #{issue_num} on {upstream_full_name} (Composite Score: {composite_score:.2f})...", file=sys.stderr)

    # 1. Check AI Policy
    policy = check_ai_policy(session, upstream_full_name)
    if policy == "disallowed":
        print(f"  AI policy disallowed for {upstream_full_name}. Skipping issue #{issue_id}.", file=sys.stderr)
        with conn.cursor() as cur:
            cur.execute("UPDATE issues SET status = 'skipped', updated_at = now() WHERE id = %s", (issue_id,))
        conn.commit()
        return

    # 2. Check Daily Budget Caps
    can_submit, cap_reason = check_daily_caps(conn, repo_id)
    if not can_submit:
        print(f"  Cap limit hit for {upstream_full_name}: {cap_reason}", file=sys.stderr)
        return

    fork_owner = fork_full_name.split("/")[0] if fork_full_name and "/" in fork_full_name else upstream_full_name.split("/")[0]

    # 3. Idempotency Check — Existing PR
    exists, existing_url, existing_num = check_existing_pr(session, upstream_full_name, fork_owner, branch_name)
    if exists:
        print(f"  PR already exists upstream for issue #{issue_num}: {existing_url} (#{existing_num})", file=sys.stderr)
        body, disclosure = build_pr_body(issue_num, issue_title, agent_name, composite_score, reviewer_score, tests_passed)
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO pr_submissions (issue_id, run_id, pr_url, pr_number, submitted_at, disclosure_text)
                VALUES (%s, %s, %s, %s, now(), %s)
                ON CONFLICT (issue_id) DO UPDATE SET
                    pr_url = EXCLUDED.pr_url,
                    pr_number = EXCLUDED.pr_number;
                UPDATE issues SET status = 'submitted', updated_at = now() WHERE id = %s;
            """, (issue_id, run_id, existing_url, existing_num, disclosure, issue_id))
        conn.commit()
        return

    # 4. Formulate & Submit PR
    pr_title = f"fix: resolve issue #{issue_num} ({issue_title})"
    pr_body, disclosure_text = build_pr_body(issue_num, issue_title, agent_name, composite_score, reviewer_score, tests_passed)

    try:
        pr_url, pr_num = create_upstream_pr(session, upstream_full_name, fork_owner, branch_name, default_branch, pr_title, pr_body)
        print(f"  Successfully submitted PR #{pr_num} for issue #{issue_num}: {pr_url}", file=sys.stderr)

        # 5. DB State Update
        with conn.cursor() as cur:
            cur.execute("""
                INSERT INTO pr_submissions (issue_id, run_id, pr_url, pr_number, submitted_at, disclosure_text)
                VALUES (%s, %s, %s, %s, now(), %s)
                ON CONFLICT (issue_id) DO UPDATE SET
                    pr_url = EXCLUDED.pr_url,
                    pr_number = EXCLUDED.pr_number;
                UPDATE issues SET status = 'submitted', updated_at = now() WHERE id = %s;
            """, (issue_id, run_id, pr_url, pr_num, disclosure_text, issue_id))
        conn.commit()

    except Exception as exc:
        conn.rollback()
        sanitized_err = sanitize_token(str(exc))
        print(f"  Failed to submit PR for issue #{issue_num}: {sanitized_err}", file=sys.stderr)


def get_authenticated_session():
    """Create GitHub Session using GitHub App (if configured) or PAT fallback."""
    if APP_ID and APP_PRIVATE_KEY:
        try:
            token = get_app_installation_token(APP_ID, APP_PRIVATE_KEY)
            print("Authenticated using resilient-bot (GitHub App token)", file=sys.stderr)
            return create_github_session(token)
        except Exception as exc:
            print(f"Warning: Failed GitHub App authentication, falling back to PAT: {exc}", file=sys.stderr)

    print("Authenticated using PAT token", file=sys.stderr)
    return create_github_session(DISPATCH_TOKEN)


def main():
    global DB_URL, DISPATCH_TOKEN, APP_ID, APP_PRIVATE_KEY
    DB_URL = os.environ.get("DATABASE_URL", "").strip()
    DISPATCH_TOKEN = os.environ.get("GITHUB_DISPATCH_TOKEN", "").strip() or os.environ.get("GITHUB_SCAN_TOKEN", "").strip()
    APP_ID = os.environ.get("GITHUB_APP_ID", "").strip() or os.environ.get("APP_ID", "").strip()
    APP_PRIVATE_KEY = os.environ.get("GITHUB_APP_PRIVATE_KEY", "").strip() or os.environ.get("APP_PRIVATE_KEY", "").strip()

    pem_path = os.environ.get("GITHUB_APP_PRIVATE_KEY_PATH", "").strip()
    if not APP_PRIVATE_KEY and pem_path and os.path.exists(pem_path):
        with open(pem_path, "r", encoding="utf-8") as f:
            APP_PRIVATE_KEY = f.read()

    if not DB_URL:
        print("Error: DATABASE_URL not set", file=sys.stderr)
        sys.exit(1)
    if not DISPATCH_TOKEN and not (APP_ID and APP_PRIVATE_KEY):
        print("Error: Neither PAT nor GitHub App credentials set", file=sys.stderr)
        sys.exit(1)

    session = get_authenticated_session()
    conn = psycopg2.connect(DB_URL)
    try:
        candidates = find_submittable_issues(conn)
        print(f"Found {len(candidates)} submittable candidate issue(s).", file=sys.stderr)

        for candidate in candidates:
            try:
                submit_issue(conn, session, candidate)
            except Exception as exc:
                conn.rollback()
                print(f"Error submitting issue #{candidate[8]}: {sanitize_token(str(exc))}", file=sys.stderr)

        print("\n=== Submission complete ===", file=sys.stderr)
    finally:
        conn.close()


if __name__ == "__main__":
    main()
